// Generated by https://quicktype.io

class TriviaProfileInfo {
  int won;
  int played;
  int score;
  String gamingLevel;

  TriviaProfileInfo({
    this.won,
    this.played,
    this.score,
    this.gamingLevel,
  });

  TriviaProfileInfo.fromJsonMap(Map<String, dynamic> json) {
    if (json==null) return;
    
    this.won          = json['won'];
    this.score        = json['score'];
    this.played       = json['played'];
    this.gamingLevel  = json['gamingLevel'] ?? '';
  }
}
